### ISSUE TITLE
Entities?

### ISSUE THREAD

**Issue by vandenbogerd** [wijnandtop/home_assistant_gardena#10]
I downloaded all files, altered my configuration.yaml and rebooted the raspberry Pi.

However, in the list of entities, I can not see anything related to Gardena.

The logs show no errors whatsoever.

**Comment by wijnandtop** [comment]
Sorry my for late reply, there are some issues with this plugin. Some people fixed issues in their own forks. I will ask them to merge them in this project.

There are also some forks which implemented support for the HACS (plugin store) for easier installation.

**Comment by wijnandtop** [comment]
HACS support is now added, do you experience the same issue using the HACS installer?

https://hacs.xyz/
