### ISSUE TITLE
Mower only runs for a few minutes

### ISSUE THREAD

**Issue by chaelli** [wijnandtop/home_assistant_gardena#14]
Hi and thanks for your work!
I use homeassistant to start my sileno when the weather is good at a certain time. But it always only starts for a few minutes. Is it possible that the unit was changed from minutes to seconds?

**Comment by Jpsy** [comment]
Do you use the "start" service to run the mower?
Works flawlessly for me.
You can also use the "return to base" service to activate the mower schedule and' "stop" to deactivate it.

**Comment by chaelli** [comment]
yes, I use start.. and then it looks like this:
![image](https://user-images.githubusercontent.com/878151/78561751-8e4a3e80-7818-11ea-9dfc-75c94ade2cc9.png)
(it actually started 13:15 - probably the timing is off, as data is only updated every 5min as far as I understand)

**Comment by chaelli** [comment]
I just made another screenshot from the gardena app:
![image](https://user-images.githubusercontent.com/878151/78596210-aab39e80-784b-11ea-9072-3bae48b397a5.png)

I changed the code to 
self.robot.start(14400) and now it runs for 4 hours. (4 * 60 * 60). So for me these are defenitely seconds.

**Comment by Jpsy** [comment]
Oh, I have to say that I never used start() with a parameter. You didn't mention that in your original posting. Did you try it without params?

**Comment by chaelli** [comment]
yes, without it will run for 24 minutes.

**Comment by northpower25** [comment]
@chaelli  please Check the following new integration from @osks with the use of the official Gardena/Husquarna https://github.com/py-smart-gardena/hass-gardena-smart-system

Thanks for your work @wijnandtop but i think the Integration of @osks is now closer to the target to become an official HA integration status with use of the official Gardena/Husquarna API

**Comment by wijnandtop** [comment]
This project is no longer supported, it was build at a time when there was no official supported Gardena API. By now there is a new implementation, with realtime interaction and supporting all gardena devices:

https://github.com/py-smart-gardena/hass-gardena-smart-system
