### ISSUE TITLE
Watercontrol button doesen‘t work

### ISSUE THREAD

**Issue by northpower25** [wijnandtop/home_assistant_gardena#15]
With HA 0.108.3 the watercontrol showed but doesen‘t work (no reaktion of the hardware device) anymore without raising any error in HA log.
![6DD1F1D6-7367-436B-AA69-25A18EC9026B](https://user-images.githubusercontent.com/36472486/79640206-98f9c180-8190-11ea-84a4-77f7ae4e6649.jpeg)

**Comment by northpower25** [comment]
as workaround i use the integration in combination with the Homekit integration for HA of Gardena. so that i can use both the sensors (that are not published over Homekit like the lawn mower integration or the soil temperatur) and the water button thats corrently not work over this custom component. I hope that i can help others and i'm hopfully that in the futur this integration works again.

**Comment by wijnandtop** [comment]
I was able to reproduce your issue, will try to take a look soon.

**Comment by northpower25** [comment]
I‘ve too switch over to -> https://github.com/py-smart-gardena/hass-gardena-smart-system

Thanks for your work @wijnandtop but i think the Integration of @osks is now closer to the target to become an official HA integration status.
