### ISSUE TITLE
With the Beta from HA 0.110 following have changed

### ISSUE THREAD

**Issue by northpower25** [wijnandtop/home_assistant_gardena#17]
In preparation for HA 0.110 the following errors are shown and make changes to the integration necessary.

othewise the following errors rising ...

SwitchDevice is deprecated, modify GardenaSmartSwitch to extend SwitchEntity
StateVacuumDevice is deprecated, modify GardenaSmartMower to extend StateVacuumEntity

**Comment by wijnandtop** [comment]
https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

Change will indeed be introduced in version 0.110 but it will still support the old classes. Will apply a change when 0.110 is available for a while so we can safely change without impacting users who wait a bit when upgrading HASS.

**Comment by northpower25** [comment]
I‘ve too switch over to -> https://github.com/py-smart-gardena/hass-gardena-smart-system

Thanks for your work @wijnandtop but i think the Integration of @osks is now closer to the target to become an official HA integration status.
