### ISSUE TITLE
home assistant 0.88

### ISSUE THREAD

**Issue by steveknoefler** [wijnandtop/home_assistant_gardena#5]
hi,
I updated to 0.88 and something changed with custom_components

new:
custom_components/gardena/ - files

but its not working if I changed it.
what happens with the gardena.py in die custom_components folder
<img width="308" alt="bildschirmfoto 2019-02-21 um 17 33 47" src="https://user-images.githubusercontent.com/13857839/53185232-e6b38200-35fe-11e9-9d38-31625897939c.png">

thanks 
bye Steve

**Comment by Jpsy** [comment]
Simply creating folders and moving and renaming the integration files there is not working. There are obviously more changes necessary. For the moment, you can stay with the old structure of "gardena.py" files in several folders. It will throw warnings in the log, but it will continue to work. I hope @wijnandtop will be able to change the structure soon, before there will be breaking changes. I would jump in and help but my knowledge of Hass components is (still) very limited.

**Comment by Jpsy** [comment]
Aaah, the solution is simple. After reading the HA dev blog, I found the missing link:

* rename / move...
  * `binary_sensor/gardena.py` to `gardena/binary_sensor.py`
  * `sensor/gardena.py` to `gardena/sensor.py`
  * `switch/gardena.py` to `gardena/switch.py`
  * `vacuum/gardena.py` to `gardena/vacuum.py`
  * `gardena.py` to `gardena/__init__.py`

The last step was the one that was missing.

**Comment by steveknoefler** [comment]
oh __init__.py was missing I haven't seen it on the debug log :/

thanks jpsy
