### ISSUE TITLE
I'm owning an irrigation control

### ISSUE THREAD

**Issue by kayloehmann** [wijnandtop/home_assistant_gardena#8]
I'm owning an irrigation control. Can i be of any help providing info to get this implemented?

**Comment by wijnandtop** [comment]
Yes, you can. I will need to create a small script which collects the responses from gardena.
If I have this data the plugin can be extended.

Not sure if I'm able to do this on a short notice. 

But if you're able to implement it yourself, feel free to send a pull-request.

**Comment by kayloehmann** [comment]
Great. Please provide me with the script. I will try. :-)
