### ISSUE TITLE
Use official API

### ISSUE THREAD

**Issue by Fabenissimo** [wijnandtop/home_assistant_gardena#9]
Hello,

please check if you can use the official API.

See https://community.home-assistant.io/t/gardena-smart-system-home-assistant/51764/66

Best regards

Fabian

**Comment by wijnandtop** [comment]
Thank you for your suggestion, would be a good improvement. 

Hope to be able to spent time on it soon, if someone else is willing to do a pull request, it is very welcome!

**Comment by northpower25** [comment]
I‘ve too switch over to -> https://github.com/py-smart-gardena/hass-gardena-smart-system

Thanks for your work @wijnandtop but i think the Integration of @osks is now closer to the target to become an official HA integration status with use of the official Gardena/Husquarna API

**Comment by wijnandtop** [comment]
This project is no longer supported, it was build at a time when there was no official supported Gardena API. By now there is a new implementation, with realtime interaction and supporting all gardena devices:

https://github.com/py-smart-gardena/hass-gardena-smart-system
